const fetch = require('node-fetch');
const wiki = require('wikijs').default;


class PageManager {
    // Generated by ChatGPT
    async getRandomPages(limit = 2) {
        try {
            const randomTitles = await wiki().random(limit);
            const titlePromises = randomTitles.map(async (title) => {
                const url = await wiki().page(title).then(page => page.url());
                return { title, url };
            });
            return Promise.all(titlePromises);
        } catch (error) {
            console.error(error);
            return [];
        }
    }
    

    // Find the shortest path between two pages.
    async getShortestPath(startTitle, endTitle) {
        return await fetch(
            'https://api.sixdegreesofwikipedia.com/paths', 
            {
                method: 'POST',
                body: JSON.stringify({source: startTitle, target: endTitle}),
                headers: {
                    'Content-Type': 'application/json',
                },
            }
        )
        .then(response => response.json())
        .then((data) => {
            return data.paths[0].map(id => data.pages[id.toString()].title);
        })
        .catch((error) => {
            throw error;
        });
    }
}

module.exports = PageManager;